[default]
template_dir = "static"

[default.databases.sqlite_database]
url = "db/db.sqlite"

[debug]
address = "127.0.0.1"
port = 5892

[release]
address = "0.0.0.0"
port = 5892
#secret_key= "$RANDOM_SECRET_KEY_HERE"
